export const ADD_BEVERAGE = "ADD_BEVERAGE";
export const DELETE_BEVERAGE = "DELETE_BEVERAGE";
export const TOGGLE_DETAILS_ON = "TOGGLE_DETAILS_ON";
export const TOGGLE_DETAILS_OFF = "TOGGLE_DETAILS_OFF";
export const TOGGLE_FORM = "TOGGLE_FORM";